version: '3.8'

services:
  node:
    build:
      context: ./.circleci/node
    volumes:
      - ./:/app
    command: yarn run start
    ports:
      - 3000:3000

  nginx:
    build:
      target: prod
      context: ./.circleci/nginx
    volumes:
      - ./build:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80